language: java

# also had to remove jdk section to use the oracle-java8-installer
# https://github.com/travis-ci/travis-ci/issues/5897#issuecomment-218354129
#jdk:
#    - oraclejdk8

# Need to use JDK 8u40+ to get around a bug that causes JMH to not compile.
# To do that, this was suggested
# https://github.com/travis-ci/travis-ci/issues/4042
addons:
  apt:
    packages:
      - oracle-java8-installer

# something about container-based builds said to do this
sudo: false
