language: java

# This thread says to remove the jdk section, but I think that's only
# if you're using the jdk_switcher with oracle-java8-installer
# https://github.com/travis-ci/travis-ci/issues/5897#issuecomment-218354129
jdk:
    - oraclejdk8

script: mvn clean package

# Need to use JDK 8u40+ to get around a bug that causes JMH to not compile.
# To do that, this was suggested
# https://github.com/travis-ci/travis-ci/issues/4042
# and here's the JDK bug I ran into (Travis was using 8u31)
# https://bugs.openjdk.java.net/browse/JDK-8067747
addons:
  apt:
    packages:
      - oracle-java8-installer

# something about container-based builds said to do this
sudo: false
